### ISSUE TITLE
Can not load mapbox-gl after yarn install

### ISSUE THREAD

**Issue by MostafaRDE** [afilabs/h3js_hexagons_taxi_demand_time_slider#1]
I installed node packages and then started it, but project has error in run on the chrome browser:
- Chrome Desktop Windows - Version 116.0.5845.141 (Official Build) (64-bit)
- Response in the browser (React error):
`Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
    at Object.Go [as transformMat4$1] (http://localhost:3000/static/js/vendors-node_modules_mapbox-gl_dist_mapbox-gl_js.chunk.js:6525:22)
    at Ho.pointRayIntersection (http://localhost:3000/static/js/vendors-node_modules_mapbox-gl_dist_mapbox-gl_js.chunk.js:25374:11)
    at Nd.pointCoordinate (http://localhost:3000/static/js/vendors-node_modules_mapbox-gl_dist_mapbox-gl_js.chunk.js:11473:46)
    at Ho.pointCoordinate (http://localhost:3000/static/js/vendors-node_modules_mapbox-gl_dist_mapbox-gl_js.chunk.js:25402:32)
    at Ho.pointCoordinate3D (http://localhost:3000/static/js/vendors-node_modules_mapbox-gl_dist_mapbox-gl_js.chunk.js:25405:42)
    at Ho.pointLocation3D (http://localhost:3000/static/js/vendors-node_modules_mapbox-gl_dist_mapbox-gl_js.chunk.js:25360:45)
    at Map.unproject (http://localhost:3000/static/js/vendors-node_modules_mapbox-gl_dist_mapbox-gl_js.chunk.js:28486:35)
    at new ar (http://localhost:3000/static/js/vendors-node_modules_mapbox-gl_dist_mapbox-gl_js.chunk.js:26002:17)
    at hr.mouseover (http://localhost:3000/static/js/vendors-node_modules_mapbox-gl_dist_mapbox-gl_js.chunk.js:26071:24)
    at Xr.handleEvent (http://localhost:3000/static/js/vendors-node_modules_mapbox-gl_dist_mapbox-gl_js.chunk.js:27078:93)`

Thanks for your support ✌️

**Comment by ZinuoCai** [comment]
Do you solve the problem? I encouter it, too. @MostafaRDE

**Comment by MostafaRDE** [comment]
@ZinuoCai
No I don't; I do not use this project anymore.

**Comment by afian** [comment]
Hi everyone,

Apologies for the problems in the project. Can you book a call with me at
https://calendly.com/afilabs.

Afian
